### ISSUE TITLE
TrackerDbContext crashes with complicated EF schema

### ISSUE THREAD

**Issue by byatis** [bilal-fazlani/tracker-enabled-dbcontext#38] opened 2015-06-23 06:08 UTC
For some reason in my EF project I get the error below when saving. This doesn't appear if I use EF DbContext instead.
"Sequence contains no matching element"
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at TrackerEnabledDbContext.Common.Extensions.TypeExtensions.GetCachedTableName(Type entityType, ITrackerContext context)
   at TrackerEnabledDbContext.Common.Extensions.TypeExtensions.<>c__DisplayClassa.<GetTableName>b__9(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at TrackerEnabledDbContext.Common.Extensions.TypeExtensions.GetFromCache[TKey,TVal](ConcurrentDictionary`2 dictionary, TKey key, Func`2 valueFactory)
   at TrackerEnabledDbContext.Common.Extensions.TypeExtensions.GetTableName(Type entityType, ITrackerContext context)
   at TrackerEnabledDbContext.Common.LogAuditor.CreateLogRecord(Object userName, EventType eventType, ITrackerContext context)
   at TrackerEnabledDbContext.Common.CommonTracker.AuditAdditions(ITrackerContext dbContext, Object userName, IEnumerable`1 addedEntries)
   at TrackerEnabledDbContext.TrackerContext.SaveChanges(Object userName)
   at MetaDB.Models.MetaDbDataContext.SaveChanges() in c:\Users\niemite\Documents\Visual Studio 2013\Projects\MetaDB\MetaDB\Models\MetaDBDataContext.cs:line 40
   at MetaDB.Controllers.ExcelImportController.Index() in c:\Users\niemite\Documents\Visual Studio 2013\Projects\MetaDB\MetaDB\Controllers\ExcelImportController.cs:line 154
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by bilal-fazlani** [comment] 2015-06-23 11:31
What are the steps to reproduce this ?
can you please send me a small code snippet that reproduces this exception ?
@byatis

**Comment by byatis** [comment] 2015-06-23 11:39
I am not sure since our Entity Model is huge and has a lot of m-m relationships with childs etc, I will try to isolate later this week if there is some single property / child object that causes this. Just added trackercontext on top of this whole model and didn't work. It did with our simpler test solution though.

**Comment by bilal-fazlani** [comment] 2015-06-23 11:42
alright. let know if you are able to narrow it down.

**Comment by bilal-fazlani** [comment] 2015-06-23 11:44
to narrow it down, 
you can download the source code from github and add reference to that project instead of nuget dll. 
then you will know what's causing this issue.

**Comment by byatis** [comment] 2015-06-23 11:47
Thanks, will try that. At least I think it is related to updating a lot of entities and subentities at the same time since all individual saves seems to work. Something to do with Local child entities or lazy loading disabled?

**Comment by bilal-fazlani** [comment] 2015-06-23 12:48
@byatis 
i think may be it has to do something with lazy loading disabled because i have tested that case.

**Comment by ScarlettCode** [comment] 2015-07-18 08:03
This is potentially fixed in the github version. Now that the tracker no longer queries the db every time it needs the original value it should be a lot less resource intensive.

**Comment by bilal-fazlani** [comment] 2015-09-28 14:24
@byatis  
could you please confirm if this is fixed for you yet or needs further investigation.
your confirmation will save a lot of time as I am planning to fix most pending defects by this weekend. 
thank you.

**Comment by byatis** [comment] 2015-09-29 07:40
Sorry for the delay, thank you very much for the fix.

This seems to work now, though it's very slow for big entities and lot's of udpates, but that is yet another issue. Can I disable tracking dynamically somehow when, for example, importing lot's of data at once?

**Comment by bilal-fazlani** [comment] 2015-09-29 09:16
Yes, you will be with the new API next week hopefully

On Tue, Sep 29, 2015 at 1:10 PM, byatis <notifications@github.com> wrote:

> Sorry for the delay, thank you very much for the fix.
>
> This seems to work now, though it's very slow for big entities and lot's
> of udpates, but that is yet another issue. Can I disable tracking
> dynamically somehow when, for example, importing lot's of data at once?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/issues/38#issuecomment-143974592>
> .
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by ixtreon** [comment] 2015-09-30 18:33
I am having the exact same problem. Using the latest git commit.

**Comment by bilal-fazlani** [comment] 2015-10-01 04:11
@ixtreon 
the latest commit doesn't have aa method called "GetCachedTableName"

could you please paste the exception stacktrace here and help me fix this defect ?

**Comment by ixtreon** [comment] 2015-10-01 14:15
@bilal-fazlani My bad, I apologise for the misreport. 
We had an older binary from a NuGet package in another project and it was overwriting the version we were building manually. Now we fixed this issue, the exception is gone. 

Thanks!

**Comment by bilal-fazlani** [comment] 2015-10-02 08:15
No worries :)

**Closed by bilal-fazlani** 2015-10-02 08:15 UTC
Labels: bug
