### ISSUE TITLE
SaveChanges logs all properties including no changes

### ISSUE THREAD

**Issue by banban** [bilal-fazlani/tracker-enabled-dbcontext#64] opened 2015-10-27 09:23 UTC
Version 3.1.0 SaveChanges logs all properties including no changes with identical OldValue and NewValue values. Does it make sense? Here is my example:
            await db.SaveChangesAsync(User.Identity.Name);
Before version 3.1.0 I used to use 2.7 and it worked correctly logging only changes.
Please update IsValueChanged void condition with
(StateOf(_dbEntry) == EntityState.Modified && prop.IsModified **&& prop.CurrentValue != prop.OriginalValue)** ;

**Comment by bilal-fazlani** [comment] 2015-10-27 14:02
No this does not make sense. This must be a bug.

On Tue, Oct 27, 2015 at 2:53 PM, banban <notifications@github.com> wrote:

> Version 3.1.0 SaveChanges logs all properties including no changes with
> identical OldValue and NewValue values. Does it make sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/issues/64>.
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by banban** [comment] 2015-10-27 23:36
Just tried to dig deeper and found that new version overrides [OriginalValue] field with new value. 
As a result, [OriginalValue] and [NewValue] are identical.
It must be a bug.

**Comment by bilal-fazlani** [comment] 2015-10-28 03:38
Cool. Thanks for the effort.
I will fix it today.

On Wed, Oct 28, 2015 at 5:06 AM, banban <notifications@github.com> wrote:

> Just tried to dig deeper and found that new version overrides
> [OriginalValue] field with new value.
> As a result, [OriginalValue] and [NewValue] are identical.
> It must be a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/issues/64#issuecomment-151675644>
> .
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by banban** [comment] 2015-10-28 23:03
Unfortunately last update does help, I cant see any changes. It still writes all properties (modified and not) to detail log. I have to use trigger to clean up that rubbish
```tsql
CREATE TRIGGER [dbo].[AuditLogDetails_ITrig] ON [dbo].[AuditLogDetails] AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	--get previous audit record new value to update current record old value
	UPDATE ald SET ald.[OriginalValue] = (
		SELECT TOP 1 pald.[NewValue] 
		FROM [dbo].[AuditLogDetails] pald 
		INNER JOIN [dbo].[AuditLogs] pal ON pald.[AuditLogId] = pal.[AuditLogId]
		WHERE al.[TypeFullName] = pal.[TypeFullName]
			AND al.[RecordId] = pal.[RecordId]
			AND ald.[PropertyName] = pald.[PropertyName]
			AND ald.Id > pald.Id
			AND ald.[AuditLogId] > pald.[AuditLogId]
		ORDER BY pald.Id DESC
	)
	FROM [dbo].[AuditLogDetails] ald
	INNER JOIN inserted i ON ald.[AuditLogId] = i.[AuditLogId]
		AND ald.[PropertyName] = i.[PropertyName]
	INNER JOIN [dbo].[AuditLogs] al ON ald.[AuditLogId] = al.[AuditLogId]

	--do not store unmodified values
	DELETE ald
	FROM [dbo].[AuditLogDetails] ald
	INNER JOIN [dbo].[AuditLogs] al ON ald.[AuditLogId] = al.[AuditLogId]
		AND al.[EventType] = 2
	INNER JOIN inserted i ON ald.[AuditLogId] = i.[AuditLogId]
	WHERE ISNULL(ald.[OriginalValue],'') = ISNULL(ald.[NewValue],'')
END
GO
```

**Comment by banban** [comment] 2015-10-28 23:06
Could you please update version from 3.1.0 to reflect changes and upload Nuget package new version.
Thanks in advance

**Comment by bilal-fazlani** [comment] 2015-10-29 03:58
Version 3.3.12 is now on nuget.
@banban , please let me know if that fixes your issue.

**Comment by bilal-fazlani** [comment] 2015-10-29 06:44
https://www.nuget.org/packages/TrackerEnabledDbContext/3.3.12

**Comment by schlippy** [comment] 2015-10-29 14:01
HI Bilal,

We have updated to v 3.3.12, and now inserts are correctly creating audit logs again. However, updates are now not creating _any_ audit records, rather than auditing every property on the entity (albeit with the same values).

Thanks for all your work on this project, it's been a great help so far.

**Comment by bilal-fazlani** [comment] 2015-10-29 14:08
Damn!
How is it possible :(  . I have many unit tests to test this functionality and the unit tests are passing.

Could you please help me reproduce this defect ?

**Comment by schlippy** [comment] 2015-10-29 14:42
What would you like me to provide in order to help? We haven't changed the attributes on our entities or the code around the context.SaveChanges method since upgrading. 

Using v2.7, entities flagged with the TrackChanges attribute were being correctly audited upon insert & update (we don't allow physical deletes, so logical deletes show up as updates).

After upgrading to 3.1, updates resulted in all properties being audited, showing the new values in both the OriginalValue and NewValue fields.

After upgrading to 3.3, updates no longer generate an AuditLog or AuditLogDetail record.

Nothing in our code base relating to the audited entities has changed between using v2.7 and v3.3.

We tried rolling back to 2.7, but now we're seeing a "sequence contains no elements" error when inserting or updating an entity flagged with TrackChanges :/

Is there anything in particular we can provide to help diagnose this?

Thanks for all your hard work, and especially for your speedy response on this.

**Comment by bilal-fazlani** [comment] 2015-10-29 14:55
No problem, I am just trying to build something useful for everyone.

Coming back to the issue,
"(we don't allow physical deletes, so logical deletes show up as updates)."
- I am working on this there there will a new status called SoftDeleted when you logically delete a record.

"After upgrading to 3.3, updates no longer generate an AuditLog or AuditLogDetail record."
- **I would like to see how are you updating an entity please.**
- Also your entity which you are trying to update
- Also your dbcontext

**Comment by schlippy** [comment] 2015-10-29 15:12
We use a repository pattern to update entities (trimmed to just show relevant code):

```c#
    public class Repository<T> where T : class
    {
        internal DbContext _context;
        internal DbSet<T> _dbSet;

        public Repository()
        {
            _context = new SCMDbContext();
            _dbSet = _context.Set<T>();
        }

        public virtual void Update(T entityToUpdate)
        {
            _dbSet.Attach(entityToUpdate);
            _context.Entry(entityToUpdate).State = EntityState.Modified;
        }
    }
```
Sample entity (trimmed):
```c#
    [TrackChanges]
    [Table("Operator")]
    public class Operator : SCMObject, ISoftDeletable
    {
        [SkipTracking]
        public int ID { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Operator_FieldLabel_CostCentre")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Shared_ErrorMessage_FieldRequired")]
        public int CostCentreId { get; set; }

        [SkipTracking]
        public int NodeId { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Operator_FieldLabel_SerialNumber")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Shared_ErrorMessage_FieldRequired")]
        [MaxLength(100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Shared_ErrorMessage_FieldMaxLength")]
        [Index("IX_SerialNumber", IsUnique = true)]
        public string SerialNumber { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Operator_FieldLabel_InternalSerialNumber")]
        [MaxLength(100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Shared_ErrorMessage_FieldMaxLength")]
        [SkipTracking]
        public string InternalSerialNumber { get; set; }
    }
```
And the context:
```c#
    public class SCMDbContext : TrackerContext
    {
        public SCMDbContext() 
            : base(ConnectionStrings.SCMConnectionString)
        {
            var initialiser = new MigrateDatabaseToLatestVersion<SCMDbContext, Migrations.Configuration>(ConnectionStrings.SCMConnectionString);

            Database.SetInitializer(initialiser);
        }

        public override int SaveChanges()
        {
            try
            {
                var username = HttpContext.Current == null 
                    ? "test.user" 
                    : HttpContext.Current.User.Identity.Name;

                return base.SaveChanges(username);
            }
            catch
            {
                return base.SaveChanges();
            }
        }
    }
```

**Comment by bilal-fazlani** [comment] 2015-10-29 15:29
Alright, thanks for the information. I will work on it and get back to you.

**Comment by schlippy** [comment] 2015-10-29 18:49
Thank you very much. 

I have updated the sample code above with the repository insert method and sample controller actions in case they can help shed any light on what is happening.

**Comment by bilal-fazlani** [comment] 2015-10-29 19:34
I have understood the problem. It's happening because in your case, context is **disconnected** from the the entity (you are attaching it manually) and hence context's changetracker doesn't have original values and considers nothing is changed, resulting in no logs.

I have found a solution for this. but it's expensive. To know what the original value was, it will have to **call database for every property** then compare original and new values and then it can log an audit record if it finds any difference.

This is usually not required when context is aware of changes. Context is aware of changes when entity is first fetched from repository and then updated and then saved. What you are doing is creating a new instance of entity yourself with updated values and then marking it as ***Modified***. Because if this, context doesn't know of entities original values. 

What you are doing is not wrong. Infact it's good for improving performance. unfortunately, in order to log changes, context will have to be aware of its original values and if you want to keep using a disconnected context, I will be able to fix logging, but it will slow down the performance. I can provide ***a new setting*** in the library where you can specify if you are using a disconnected context.

However, my personal opinion would be - since you want auditing, avoid using a disconnected context. It will result in too many database calls.

Anyways, I will provide the new setting by tomorrow and release it on nuget.

**Comment by bilal-fazlani** [comment] 2015-10-29 19:40
For example, 

the following is not a disconnected context:

```c#
var entity = db.Entities.Find(4); //Id =4, OriginalName = "Bob"
entity.Name = "Bilal" //update
db.SaveChanges();
```

here, context was aware of entities original values because context fetched it from database.

Disconnected context is when

```c#
var entity = new Entity
{
    Id = 4,
    Name = "bilal"
}

db.Entities.Attach(entity);
db.Entry(entity).Status = Status.Modified;
db.SaveChanges();
```

FYI: Disconnected context is also when entity is fetched from and saved using different instances of context.

**Comment by banban** [comment] 2015-10-29 21:53
I can also state that v 3.3.12 does not track changes at all :(.
If you have problem to identify old value, just use my trigger above to update original values. It will allow offset it to database level.

**Comment by bilal-fazlani** [comment] 2015-10-30 09:23
https://www.nuget.org/packages/TrackerEnabledDbContext/3.3.13

I have uploaded this packages to fix the issue with updates. 

Although i have updated unit tests to account for this defect, please let me know if this solves the problem.

Thank you.

**Comment by bilal-fazlani** [comment] 2015-10-30 10:00
PS: 

For this solution to work
On your application startup,
do this: 

```c#
GlobalTrackingConfig.DisconnectedContext = true;
```

**Comment by schlippy** [comment] 2015-10-30 10:22
Hi Bilal,

Thanks for takign the time to look into this. However, can I point out this code fragment from the Edit controller method:

```c#
    var toUpdate = _dataService.OperatorRepository.GetByID(model.ID);

    _mappingEngine.Map(model, toUpdate);

    _dataService.OperatorRepository.Update(toUpdate);
    _dataService.Save();
```

We retrieve objects from the context immediately prior to updating them in order to avoid the problems associated with disconnecting objects from the context.

Please note that the code posted above was working fine with v2.7, and our code base has not changed in some months now.

**Comment by bilal-fazlani** [comment] 2015-10-30 17:27
@schlippy ,  just out of curiosity , why would you even need an update method on repository then ?
the following code should just work fine, right ?

```c#
    var toUpdate = _dataService.OperatorRepository.GetByID(model.ID);

    _mappingEngine.Map(model, toUpdate);
    // commented call to update method
    // _dataService.OperatorRepository.Update(toUpdate);
    _dataService.Save();
```

from what I can see the entity is fetched from the same instance of _context. why would you need to manually attach an entity and specify its status to modified ?

```c#
_dbSet.Attach(entityToUpdate);
_context.Entry(entityToUpdate).State = EntityState.Modified;
```

**Comment by schlippy** [comment] 2015-10-30 17:52
You are absolutely right, I'm being an idiot. Not only is the call to the update method not required, but removing it means the logging works perfectly.

I suspect the update method was implemented like that to allow disconnected updates if they were needed, but has been (incorrectly) invoked by developers seeing an update method on the repository and assuming it needed calling in all instances. Given that the record got updated either way, no-one has noticed until you pointed it out!

Thanks for all your help on the matter, and for providing such an elegant and lightweight auditing plugin.

**Comment by bilal-fazlani** [comment] 2015-10-30 18:12
cool. glad I was able to help. cheers

**Closed by bilal-fazlani** 2015-10-30 18:12 UTC
Labels: bug
